### ISSUE TITLE
Vote bug

### ISSUE THREAD

**Issue by Shelly7w7** [TwistedAsylumMC/BetterVoting#11]
Sometimes when player vote, and type /vote ingame multiple times it says "``Vote is processing``" and never processes it.

**Comment by kevinmoorenyt** [comment]
if ill type /vote then my server crashes

**Comment by xDanub** [comment]
I have the issue Shelly has described aswell.

**Comment by TwistedAsylumMC** [comment]
Should be fixed in https://github.com/TwistedAsylumMC/BetterVoting/commit/7092e64a793f2d38b737a7c55eabbe1c2ec1ead8 & https://github.com/TwistedAsylumMC/BetterVoting/commit/c9f6807eee917d0ee2cfd6a77a259da9cff953d1, updating release on poggit now
