### ISSUE TITLE
Crashes server 

### ISSUE THREAD

**Issue by lazerDEV** [TwistedAsylumMC/BetterVoting#14]
Hello, when i used the github file plugin the plugin crashes the server because of stop processing and when i use the poggit phar it says vote processing.
[Wed_Apr_17-07.08.27-UTC_2019.log](https://github.com/TwistedAsylumMC/BetterVoting/files/3088345/Wed_Apr_17-07.08.27-UTC_2019.log)

**Comment by TwistedAsylumMC** [comment]
Fixed in https://github.com/TwistedAsylumMC/BetterVoting/commit/599d3fe96fff565b56293c2618ac79792959e56c
