### ISSUE TITLE
MysteryCrate-BetterVoting Bug

### ISSUE THREAD

**Issue by Maxl025** [TwistedAsylumMC/BetterVoting#19]
I use a plugin with crates and keys. Its named MysteryCrate. Theres a Vote Key. I put the command to get the key in the Bettervoting config ("key vote {real_name} 1".
But when a user votes with a name with a space and numbers after the space in it he gets more keys. Example name: Bot 1234 (He will get 1234 keys) 
Ingame you can do /key vote "Bot 1234" 1 
Then He gets 1 key because of the ". But in the config of BetterVoting you cant do "key vote "{real_name}" 1" because there are 4 instead of 2 ".

Pls help or fix this I cant solve this.
Sorry for my bad English. ;)

**Comment by TwistedAsylumMC** [comment]
Sorry for the late reply, try making the command ``"key vote \"{real_name}\" 1"
