### ISSUE TITLE
Spamming Votes

### ISSUE THREAD

**Issue by splexpe** [TwistedAsylumMC/BetterVoting#21]
For some reason , a few people can spam vote , like for example , /vote , for me says "You have already voted today!" , but for them they vote multiple times and get alot of rewards. TBH this needs to be fixed ASAP in my opinion.
![votebug](https://user-images.githubusercontent.com/46957762/74424068-ebc49f00-4e16-11ea-9ca3-6e9eba7564a8.PNG)

**Comment by splexpe** [comment]
I have investigated more into this matter and found that its only players with spaced names.
For example,

StabbzL tries to use this command more than once and he cant,
Although MCPE CHANNEL YT can, aswell as Jober Mada

**Comment by TwistedAsylumMC** [comment]
Does this only occur when spamming /vote?

**Comment by TwistedAsylumMC** [comment]
This has been fixed in 2.0.
