### ISSUE TITLE
[BUG] Plugin Crashes

### ISSUE THREAD

**Issue by brokiem** [TwistedAsylumMC/BetterVoting#23]

**Comment by brokiem** [comment]
06:39:56] [Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "plugins/BetterVoting.phar/src/twisted/bettervoting/BetterVoting" at line 77

BetterVoting 2.0

**Comment by jaylac2000** [comment]
use dev 22 for now

**Comment by TwistedAsylumMC** [comment]
Your config is invalid
