### ISSUE TITLE
/vote commands not working

### ISSUE THREAD

**Issue by SmexyDuk** [TwistedAsylumMC/BetterVoting#24]
I installed the plugin and tried typing /vote, nothing happens. When I tried voting on the voting site and did /vote, the command went through. Nothing shows up when I type /vote reload, info, top. Is currently using version 2.0.0 running 1.14.60 pocketmine. Any idea how to put links when a player types /vote as well? That'll be nice, thanks!

**Comment by SmexyDuk** [comment]
Now it doesn't work, literally not a single command and not receiving rewards.

**Comment by TwistedAsylumMC** [comment]
Fixed in https://github.com/TwistedAsylumMC/BetterVoting/commit/78334520c28e21dc41078e57c1e541cd4dcd1464
