### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MonoAdrian23** [TwistedAsylumMC/BetterVoting#32]
[14:37:13] [Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "plugins/BetterVoting-1.phar/src/twisted/bettervoting/BetterVoting" at line 77

Bettervoting 2.0.1
Pocketmine 3.14.1

**Comment by MonoAdrian23** [comment]
14:52:00] [Server thread/CRITICAL]: TypeError: "explode() expects parameter 2 to be string, null given" (EXCEPTION) in "plugins/BetterVoting-1.phar/src/twisted/bettervoting/BetterVoting" at line 78

Items to be given cant be removed

**Comment by Aericio** [comment]
Configuration error, if you need help then paste your config here.

**Comment by MonoAdrian23** [comment]
API Key from https://minecraftpocket-servers.com/servers/manage/.
commands:
    # Commands to be executed when a player claims their vote.
    # They should not include the first "/" and they should be encased in quotes.
    # It is recommended to encase the username variable in escaped quotes (\") to make sure it
    #  is sent as one argument to the command to ensure they get all of their rewards.
    # List of useable variables:
    #  {username}: The player's in game username
    #  {displayname}: The player's display/nick name
    #  {x}: The player's X coordinate
    #  {y}: The player's Y coordinate
    #  {z}: The player's Z coordinate
    - "say {username} §bHat gevotet!"
    - "givemoney \"{username}\" 1000"
    - "whatcrates key give \"{username}\" vote 1!"
# If droprewards is true, rewards will be dropped on the floor if a player's inventory is full
# If droprewards if false, rewards will dissapear if a player's inventory is full
droprewards: true
items:
    # Items to be given to a player when they claim their vote.
    # They should follow the format: "item_name:meta:amount:name:enchant_name:enchant_level".
    #  "name" can either be a custom name, or "default" to have no custom name.
    #  "item_name", "meta", "amount" & "name" must all come before any enchantments.
    #  "enchant_name:enchant_level" can be repeated as many times as you want.
    # Enchantments from PiggyCustomEnchants are also supported, use them the same as regular enchants.
    # They should also always be encased in quotes to make sure they get parsed properly.
    - ""
messages:
    info:
        title: "&aThis server's vote information:"
        content: "&aLaufzeit: {uptime}\n&aPunkte: {score}\n&aRang: {rank}\n&aVotes: {votes}\n&aFavoriten: {favorited}\n&aKommentare: {comments}"
    noperms: "&cYou do not have permission to use this command."
    reload:
        success: "&aYou have reloaded the server's vote configuration."
    top:
        novoters: "&cDerzeit keine TopVoter."
        title: "&aTopVoter dieses Monats:"
        format: "&a{place}. {username}: {votes}"
    vote:
        alreadyclaimed: "&cDu hast deinen Vote bereits eingelöst."
        alreadyprocessing: "&cDein Vote ist in Bearbeitung."
        claimed: "&bVielen Dank für dein Vote! Du hast deine Belohnung erhalten."
        error: "&cDerzeit nicht möglich, warte bitte etwas."
        notvoted: "&cDu hast noch nicht gevotet LOL."
        processing: "&aDein Vote ist in Bearbeitung, warte etwas."
        usage:
            notplayer: "&cNutze '/vote <info|reload|top>'."
            other: "&cNutze '/vote [info|top]."
            reloadperm: "&cNutze '/vote [info|reload|top]."
