### ISSUE TITLE
Player Namespace

### ISSUE THREAD

**Issue by MonoAdrian23** [TwistedAsylumMC/BetterVoting#38]
Players with namespace cant Vote.
I use the latest Release Version 2.0.2 Pocketmine 3.15.1

**Comment by KingOfTurkey38** [comment]
![image](https://user-images.githubusercontent.com/51199432/94034718-9dbb4500-fdc2-11ea-9623-8005cff5ea0a.png) it works fine for me

**Comment by KingOfTurkey38** [comment]
![image](https://user-images.githubusercontent.com/51199432/94035270-2934d600-fdc3-11ea-8c9a-54c4bc2e7a58.png)
It works fine for me
